### Convert to CSV and  Change label as original dataset: -1 -> 1 and 1 -> 0

In [19]:
import pandas as pd
file_path = 'diabetes_scale.txt'
with open(file_path, 'r') as file:
    lines = file.readlines()
data = []
for line in lines:
    parts = line.strip().split()
    label = parts[0]
    features = {int(f.split(':')[0]): float(f.split(':')[1]) for f in parts[1:]}
    features['label'] = label
    data.append(features)
df = pd.DataFrame(data)
sorted_columns = sorted([col for col in df.columns if isinstance(col, int)])
df = df[['label'] + sorted_columns]
df['label'] = df['label'].astype(int)
df['label'] = df['label'].replace({1: 0, -1: 1})
csv_file_path = 'Csv_File.csv'
df.to_csv(csv_file_path, index=False)
print(f"CSV file saved at: {csv_file_path}")
df.head(16)

CSV file saved at: Csv_File.csv

,label,1,2,3,4,5,6,7,8
0,1,-0.294118,0.487437,0.180328,-0.292929,-1.000000,0.001490,-0.531170,-0.033333
1,0,-0.882353,-0.145729,0.081967,-0.414141,-1.000000,-0.207153,-0.766866,-0.666667
2,1,-0.058824,0.839196,0.049180,-1.000000,-1.000000,-0.305514,-0.492741,-0.633333
3,0,-0.882353,-0.105528,0.081967,-0.535354,-0.777778,-0.162444,-0.923997,-1.000000
4,1,-1.000000,0.376884,-0.344262,-0.292929,-0.602837,0.284650,0.887276,-0.600000
5,0,-0.411765,0.165829,0.213115,-1.000000,-1.000000,-0.236960,-0.894962,-0.700000
6,1,-0.647059,-0.216080,-0.180328,-0.353535,-0.791962,-0.076006,-0.854825,-0.833333
7,0,0.176471,0.155779,-1.000000,-1.000000,-1.000000,0.052161,-0.952178,-0.733333
8,1,-0.764706,0.979899,0.147541,-0.090909,0.283688,-0.090909,-0.931682,0.066667
9,1,-0.058824,0.256281,0.573770,-1.000000,-1.000000,-1.000000,-0.868488,0.100000
10,0,-0.529412,0.105528,0.508197,-1.000000,-1.000000,0.120715,-0.903501,-0.700000
11,1,0.176471,0.688442,0.213115,-1.000000,-1.000000,0.132638,-0.608027,-0.566667
12,0,0.176471,0.396985,0.311475,-1.000000,-1.000000,-0.192250,0.163962,0.200000
13,1,-0.882353,0.899497,-0.016393,-0.535354,1.000000,-0.102832,-0.726729,0.266667
14,1,-0.411765,0.668342,0.180328,-0.616162,-0.586288,-0.230999,-0.565329,NaN
15,1,-0.176471,0.005025,-1.000000,-1.000000,-1.000000,-0.105812,-0.653288,-0.633333

#### KNN Imputer for missing values

In [21]:
from sklearn.impute import KNNImputer
missing_values = df.isnull().sum()
imputer = KNNImputer(n_neighbors=5)
imputed_data = imputer.fit_transform(df.drop(columns=['label']))
df_imputed = pd.DataFrame(imputed_data, columns=df.columns[1:]) 
df_imputed['label'] = df['label'] 
df_imputed = df_imputed[['label'] + list(df.columns[1:])]
csv_imputed_file_path = 'Imputed_Csv_File.csv'
df_imputed.to_csv(csv_imputed_file_path, index=False)
print(f"Imputed CSV file saved at: {csv_imputed_file_path}")
df_imputed
df_imputed.head(15)

Imputed CSV file saved at: Imputed_Csv_File.csv

,label,1,2,3,4,5,6,7,8
0,1,-0.294118,0.487437,0.180328,-0.292929,-1.000000,0.001490,-0.531170,-0.033333
1,0,-0.882353,-0.145729,0.081967,-0.414141,-1.000000,-0.207153,-0.766866,-0.666667
2,1,-0.058824,0.839196,0.049180,-1.000000,-1.000000,-0.305514,-0.492741,-0.633333
3,0,-0.882353,-0.105528,0.081967,-0.535354,-0.777778,-0.162444,-0.923997,-1.000000
4,1,-1.000000,0.376884,-0.344262,-0.292929,-0.602837,0.284650,0.887276,-0.600000
5,0,-0.411765,0.165829,0.213115,-1.000000,-1.000000,-0.236960,-0.894962,-0.700000
6,1,-0.647059,-0.216080,-0.180328,-0.353535,-0.791962,-0.076006,-0.854825,-0.833333
7,0,0.176471,0.155779,-1.000000,-1.000000,-1.000000,0.052161,-0.952178,-0.733333
8,1,-0.764706,0.979899,0.147541,-0.090909,0.283688,-0.090909,-0.931682,0.066667
9,1,-0.058824,0.256281,0.573770,-1.000000,-1.000000,-1.000000,-0.868488,0.100000
10,0,-0.529412,0.105528,0.508197,-1.000000,-1.000000,0.120715,-0.903501,-0.700000
11,1,0.176471,0.688442,0.213115,-1.000000,-1.000000,0.132638,-0.608027,-0.566667
12,0,0.176471,0.396985,0.311475,-1.000000,-1.000000,-0.192250,0.163962,0.200000
13,1,-0.882353,0.899497,-0.016393,-0.535354,1.000000,-0.102832,-0.726729,0.266667
14,1,-0.411765,0.668342,0.180328,-0.616162,-0.586288,-0.230999,-0.565329,-0.440000